return {
  m_Name = "Ecosystem",
  Type = 3,
  StartingCard = "nature_conservation",
  StartingZoneIncreaseCost = {
    Production = 1,
    People = 1,
    Science = 0
  },
  StartingSpeed = 0,
  CardData = "card_manager",
  Cards = {
    "amazon_reforestation",
    "ecosystem_prioritization",
    "nature_conservation",
    "rainwater_harvest",
    "agroforestry",
    "permaculture",
    "natural_hedges",
    "local_solutions",
    "corals_restoration",
    "ecosystem_restoration",
    "protected_landscapes",
    "ecocentrism",
    "agroecology",
    "kelp_plantation",
    "carbon_storing_pasture",
    "mass_reforestation",
    "mangroves_planting",
    "ecosystem_engineers",
    "biophilia",
    "regenerative_agriculture",
    "carbon_agriculture",
    "world_climate_fund",
    "resistant_crops",
    "lab_food",
    "robobees",
    "green_deserts",
    "30by30",
    "aquaponics",
    "precision_agriculture",
    "hydropony",
    "ecosystems_of_22th_century"
  },
  Background1 = "karta_EC_bcground1.png",
  Background2 = "karta_EC_bcground2.png",
  DefaultCardIllustration = "karta_EC_permaculture_IL_BW.png",
  ScriptFile = "SectorCardSO.cs"
}