return {
  m_Name = "Production",
  Type = 1,
  StartingCard = "industry20",
  StartingZoneIncreaseCost = {
    Production = 1,
    People = 1,
    Science = 0
  },
  StartingSpeed = 0,
  CardData = "card_manager",
  Cards = {
    "pollution_regulations",
    "desalination",
    "safer_nuclear",
    "hydroenergy",
    "renewable_energy",
    "wind_energy",
    "solar_energy",
    "fusion_power",
    "wave_hydro_plants",
    "solar_subsidies",
    "therma_drill",
    "miracle_enzym",
    "more_coal",
    "cleaner_fossil",
    "nuclear_energy",
    "Non_renewable_energy",
    "gas_power_plants",
    "home_wind_farms",
    "solar_energy_2.0",
    "fusion3_0",
    "biodiversity_credits",
    "controlled_weather",
    "massive_automation",
    "nuclear2_0",
    "massive_extraction",
    "modular_nuclear_reactor",
    "offshore_wind_farms",
    "deep_sea_mining",
    "sahara_solar_field",
    "giant_hydroplants",
    "modular_fusion_reactors",
    "fracking",
    "industry20",
    "industry22"
  },
  Background1 = "karta_IN_bcground1.png",
  Background2 = "karta_IN_bcground2.png",
  DefaultCardIllustration = "karta_IN_gas_power_plants_IL_BW.png",
  ScriptFile = "SectorCardSO.cs"
}