return {
  m_Name = "People",
  Type = 2,
  StartingCard = "societal_change",
  StartingZoneIncreaseCost = {
    Production = 1,
    People = 1,
    Science = 0
  },
  StartingSpeed = 0.4444,
  CardData = "card_manager",
  Cards = {
    "no_tech_civilisation",
    "tribal_culture",
    "rage_againts_machines",
    "voluntary_modesty",
    "lifestyle_changes",
    "circular_economy",
    "guerrilla_gardening",
    "carbon_tax",
    "degrowth",
    "societal_change",
    "idea_incubator",
    "loss_damage",
    "refugee_integration",
    "decarbonisation_law",
    "carbon_tax_2.0",
    "mass_airconditioning",
    "transition_from_fossils",
    "electric_transport",
    "energy_efficient_cities",
    "carbon_tax_3.0",
    "decentralised_economy",
    "doughnut_economy",
    "electric_transport_2.0",
    "decentralised_power_grid",
    "modified_babies",
    "net_zero",
    "vr_fully_utopia",
    "eco_symbiosis"
  },
  Background1 = "karta_PL_bcground1.png",
  Background2 = "karta_PL_bcground2.png",
  DefaultCardIllustration = "karta_PL_energy_efficient_cities_IL_BW.png",
  ScriptFile = "SectorCardSO.cs"
}