return {
  m_Name = "Science",
  Type = 4,
  StartingCard = "science_funding",
  StartingZoneIncreaseCost = {
    Production = 0,
    People = 1,
    Science = 1
  },
  StartingSpeed = 0,
  CardData = "card_manager",
  Cards = {
    "reflective_sheets",
    "emission_clean",
    "carbon_capture",
    "carbon_capture2",
    "smog_sucking_vacuum",
    "space_research",
    "habitable_planet",
    "moon_commuting",
    "vr_worlds",
    "human_engineering",
    "incubator",
    "research centers",
    "carbon_capture3",
    "geoengineering",
    "artificial_ecosystems",
    "coastal_bariers",
    "artificial_corals",
    "batteries",
    "atmospheric_aerosols",
    "meteo_models",
    "chosen_people_left",
    "advanced_robotics",
    "radiative_cooling",
    "science_funding",
    "space_mirrors",
    "planet_b_colonised",
    "planetary_thermostat"
  },
  Background1 = "science_atlas_card_SC_background1.png",
  Background2 = "science_atlas_card_SC_background2.png",
  DefaultCardIllustration = "science_atlas_karta_SC_robobees_IL_BW.png",
  ScriptFile = "SectorCardSO.cs"
}